name: Tests

on: [push]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Check
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: check

      - name: Build Coverage Report
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: coverageReport

      - name: Upload Coverage Report
        uses: codecov/codecov-action@v1
        with:
          file: ./build/reports/jacoco/coverageReport/coverageReport.xml